# Generated by Django 4.1 on 2023-10-23 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook_receiver', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='payload',
        ),
        migrations.AddField(
            model_name='notification',
            name='callerId',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='digits',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='recipient',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='speechResult',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
