# Generated by Django 4.1 on 2023-10-25 21:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook_receiver', '0002_remove_notification_payload_notification_callerid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='callerId',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator('^\\+\\d{1,19}$', 'Enter a valid phone number starting with +')]),
        ),
        migrations.AlterField(
            model_name='notification',
            name='confidence',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='notification',
            name='digits',
            field=models.CharField(blank=True, max_length=1, null=True, validators=[django.core.validators.RegexValidator('^[0-9]$')]),
        ),
        migrations.AlterField(
            model_name='notification',
            name='recipient',
            field=models.CharField(default='not-captured', max_length=20, validators=[django.core.validators.RegexValidator('^\\+\\d{1,19}$', 'Enter a valid phone number starting with +')]),
        ),
    ]
