# Generated by Django 4.1 on 2023-10-25 21:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook_receiver', '0003_alter_notification_callerid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='recipient',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\+\\d{1,19}$', 'Enter a valid phone number starting with +')]),
        ),
    ]
